---
- name: Configure Rocky Linux Server
  hosts: all
  become: yes
  vars:
    ansible_connection: ssh
    ansible_transfer_method: scp
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update and upgrade all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Ensure /etc/ssh/sshd_config.d directory exists
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d
        owner: root
        group: root
        mode: '0755'

    - name: Add override file to disable SSH password login
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/00-disable-ssh-password.conf
        content: |
          PasswordAuthentication no
          ChallengeResponseAuthentication no
        owner: root
        group: root
        mode: '0644'

    - name: Check if Docker repository is already present
      ansible.builtin.stat:
        path: /etc/yum.repos.d/docker-ce.repo
      register: docker_repo

    - name: Add Docker repo
      ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: not docker_repo.stat.exists

    - name: Install Docker
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Check if Docker Swarm is initialized
      ansible.builtin.command:
        cmd: docker info
      register: swarm_status
      changed_when: false

    - name: Initialize Docker Swarm
      ansible.builtin.command:
        cmd: docker swarm init
      when: "'Swarm: inactive' in swarm_status.stdout"

    - name: Remove default linuxuser user if it exists
      ansible.builtin.user:
        name: linuxuser
        state: absent
        remove: yes

    - name: Ensure discord-bot-user exists
      ansible.builtin.user:
        name: bot-manager
        state: present
        create_home: no
        groups: docker
        append: yes
        shell: /usr/sbin/nologin

    - name: Remove bot-manager's home directory if it exists
      ansible.builtin.file:
        path: /home/bot-manager
        state: absent

    - name: Create Docker config directory for bot-manager
      ansible.builtin.file:
        path: /etc/docker/bot-manager
        state: directory
        owner: bot-manager
        group: bot-manager
        mode: '0750'

    - name: Add DOCKER_CONFIG to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'DOCKER_CONFIG=/etc/docker/bot-manager'
        create: yes

    - name: Add DOCKER_CONFIG line after Defaults env_keep line
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        insertafter: '^#\s*Defaults\s+env_keep\s*\+=\s*"HOME"'
        line: 'Defaults env_keep += "DOCKER_CONFIG"'
        state: present
        validate: '/usr/sbin/visudo -cf %s'

    - name: Add /usr/local/bin to sudoers secure_path
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^Defaults\s+secure_path\s*=\s*.*'
        line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
        state: present
        validate: '/usr/sbin/visudo -cf %s'

    - name: Install pass utility
      ansible.builtin.package:
        name: pass
        state: present

    - name: Install GPG
      ansible.builtin.package:
        name: gnupg2
        state: present

    - name: Create GPG key configuration file
      ansible.builtin.copy:
        dest: /root/gpg_key_config
        content: |
          %echo Generating a Docker GPG key
          Key-Type: RSA
          Key-Length: 2048
          Name-Real: DockerCredential
          Name-Email: docker@example.com
          Expire-Date: 0
          %no-protection
          %commit
          %echo Done

    - name: Generate GPG key non-interactively using config file
      ansible.builtin.command:
        cmd: gpg --batch --generate-key /root/gpg_key_config

    - name: Get GPG key ID
      ansible.builtin.command:
        cmd: gpg --list-secret-keys --keyid-format LONG
      register: gpg_keys

    - name: Extract GPG key ID
      ansible.builtin.set_fact:
        gpg_key_id: "{{ gpg_keys.stdout.split('\n') | select('search', 'sec') | map('regex_search', '[A-F0-9]{16}') | first }}"

    - name: Initialize pass for bot-manager with GPG key
      ansible.builtin.command: pass init "{{ gpg_key_id }}"
      become_user: bot-manager
      when: gpg_key_id is defined

    - name: Download docker-credential-pass v0.8.2 binary from GitHub releases
      ansible.builtin.get_url:
        url: "https://github.com/docker/docker-credential-helpers/releases/download/v0.8.2/docker-credential-pass-v0.8.2.linux-amd64"
        dest: /usr/local/bin/docker-credential-pass
        mode: '0755'

    - name: Ensure the docker-credential-pass binary is executable
      ansible.builtin.file:
        path: /usr/local/bin/docker-credential-pass
        mode: '0755'

    - name: Configure Docker to use the credential store in /etc/docker/bot-manager
      ansible.builtin.copy:
        content: |
          {
            "credsStore": "pass"
          }
        dest: /etc/docker/bot-manager/config.json
        owner: bot-manager
        group: bot-manager
        mode: '0644'

    - name: Ensure /opt/discord-bots and bot subdirectory exist
      ansible.builtin.file:
        path: "/opt/discord-bots/{{ item }}"
        state: directory
        mode: '0700'
        owner: bot-manager
        group: bot-manager
      loop:
        - ""
        - "ics-bot"