---
- name: Configure Rocky Linux Server
  hosts: all
  become: yes
  vars:
    ansible_connection: ssh
    ansible_transfer_method: scp
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update and upgrade all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Check if Docker repository is already present
      ansible.builtin.stat:
        path: /etc/yum.repos.d/docker-ce.repo
      register: docker_repo

    - name: Add Docker repo
      ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: not docker_repo.stat.exists

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Check if Docker Swarm is initialized
      ansible.builtin.command:
        cmd: docker info
      register: swarm_status
      changed_when: false

    - name: Initialize Docker Swarm
      ansible.builtin.command:
        cmd: docker swarm init
      when: "'Swarm: inactive' in swarm_status.stdout"

    - name: Remove default linuxuser user if it exists
      ansible.builtin.user:
        name: linuxuser
        state: absent
        remove: yes

    - name: Ensure discord-bot-user exists
      ansible.builtin.user:
        name: bot-manager
        state: present
        create_home: no
        groups: docker
        append: yes
        shell: /usr/sbin/nologin

    - name: Remove bot-manager's home directory if it exists
      ansible.builtin.file:
        path: /home/bot-manager
        state: absent

    - name: Create Docker config directory for bot-manager
      ansible.builtin.file:
        path: /etc/docker/bot-manager
        state: directory
        owner: bot-manager
        group: bot-manager
        mode: '0750'

    - name: Add DOCKER_CONFIG to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'DOCKER_CONFIG=/etc/docker/bot-manager'
        create: yes

    - name: Add DOCKER_CONFIG line after Defaults env_keep line
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        insertafter: '^#\s*Defaults\s+env_keep\s*\+=\s*"HOME"'
        line: 'Defaults env_keep += "DOCKER_CONFIG"'
        state: present
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ensure /opt/discord-bots and bot subdirectory exist
      ansible.builtin.file:
        path: "/opt/discord-bots/{{ item }}"
        state: directory
        mode: '0700'
        owner: bot-manager
        group: bot-manager
      loop:
        - ""
        - "ics-bot"