name: Create prod snapshot on release

on:
  release:
    types:
      - published

jobs:
  create_prod_snapshot:
    runs-on: ubuntu-latest
    env:
      PKR_VAR_image_tag: prod-${{ github.event.release.tag_name }}
      PKR_VAR_vultr_api_key: ${{ secrets.VULTR_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible using pip
        run: |
          pip install --upgrade pip
          pip install ansible

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3

      - name: Packer Init
        run: |
          source ansible-env/bin/activate
          cd vultr && packer init main.pkr.hcl

      - name: Packer Build
        run: |
          source ansible-env/bin/activate
          cd vultr && packer build main.pkr.hcl