name: Create test snapshot on PR

on:
  pull_request:
    branches:
      - main

jobs:
  create_test_snapshot:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PKR_VAR_image_tag: test-PR#${{ github.event.pull_request.number }}
      PKR_VAR_vultr_api_key: ${{ secrets.VULTR_API_KEY }}
      HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
      HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
      HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
      HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
      HCP_PKR_BUCKET: discord-bot-server
      HCP_PKR_CHANNEL: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible using pip
        run: |
          pip install --upgrade pip
          pip install ansible

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3

      - name: Packer Init
        run: |
          cd vultr
          packer init main.pkr.hcl

      - name: Packer Build
        id: packer_build
        run: |
          cd vultr
          packer_output=$(mktemp)
          packer build main.pkr.hcl | tee $packer_output
          packer_output=$(cat $packer_output)
          echo "::set-output name=packer_output::$packer_output"

      - name: Get Version Fingerprint
        id: get_version_fingerprint
        run: |
          version_fingerprint=$(echo "${{ steps.packer_build.outputs.packer_output }}" | grep -oP 'Tracking build on HCP Packer with fingerprint "\K[^"]+')
          if [[ -z "$version_fingerprint" ]]; then
            echo "Error: Unable to extract version fingerprint"
            exit 1
          else
            echo "Version fingerprint: $version_fingerprint"
            echo "::set-output name=version_fingerprint::$version_fingerprint"
          fi

      - name: Fetch Access Token
        id: fetch_access_token
        run: |
          response=$(curl --silent --location "https://auth.idp.hashicorp.com/oauth2/token" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "client_id=$HCP_CLIENT_ID" \
            --data-urlencode "client_secret=$HCP_CLIENT_SECRET" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "audience=https://api.hashicorp.cloud")
          hcp_access_token=$(echo $response | jq -r '.access_token')
          if [[ -z "$hcp_access_token" ]]; then
            echo "Error: Unable to extract access token"
            exit 1
          else
            echo "HCP access token: $hcp_access_token"
            echo "::set-output name=hcp_access_token::$hcp_access_token"

      - name: Update Assigned Version of Development Channel
        run: |
          curl --location -X PATCH "https://api.cloud.hashicorp.com/packer/2023-01-01/organizations/$HCP_ORGANIZATION_ID/projects/$HCP_PROJECT_ID/buckets/$HCP_PKR_BUCKET/channels/$HCP_PKR_CHANNEL" \
            --header "Authorization: Bearer ${{ steps.fetch_access_token.outputs.hcp_access_token }}" \
            --header "Content-Type: application/json" \
            --data "{
              'version_fingerprint': '"'${{ steps.get_version_fingerprint.outputs.version_fingerprint }}'"',
              'update_mask': 'versionFingerprint'
            }"